body:
  - type: markdown
    attributes:
      value: |
        Please fill out the template below to help us understand your issue better. This will help us provide a more accurate and faster response. Try to be as precise as possible.
        Consider the following hints: 
        - Never make screenshots of code, but paste the text
        - In case of exceptions, always include the first exception
  - type: input
    id: matsim-version
    attributes:
      label: Provide the MATSim version you are using. You can find the version in the `pom.xml`. E.g. `2025.0`.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Did you build a minimal example to reproduce the issue?
      description: | 
        If you are facing an issue, please try to create a minimal example that reproduces the problem. This will help us understand the issue better and provide a more accurate response. 
        This means in particular: Provide an example with a minimal population, network and config to start the simulation with one click/command that gives the error message.
      options:
        - label: Yes
          required: true
    validations:
      required: true
  - type: textarea
    id: problem-description
    attributes:
      label: Describe the problem you are facing.
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: If possible, provide a link to your minimal example. This might be a GitHub repository.
  - type: textarea
    id: background
    attributes:
      label: If you want, provide some background information about you and your project. This might help us understand your issue better.